spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  devtools:
    restart:
       enabled: true
    livereload:
       enabled: false
  redis:
    host: localhost
    port: 6379
  datasource:
    # type: com.zaxxer.hikari.HikariDataSource
    # url: jdbc:mysql://localhost:3306/catalogdev?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1
    username: catalogdev
    password:
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
        hibernate.id.new_generator_mappings: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
    port: 8080
---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=utf8&useSSL=false 
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2
  datasource:
    initialize: false