spring:
  profiles:
    active: dev
  data:
    rest:
      basePath: /api
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
logging.level.org.springframework.security: DEBUG
spring:
  profiles: dev
  datasource:
    # type: com.zaxxer.hikari.HikariDataSource
    # url: jdbc:mysql://localhost:3306/catalogdev?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1
    username: localdev
    password:
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
        #ddl-auto: create-drop
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
        hibernate.id.new_generator_mappings: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
security.ignored: /resources/**
---
server:
  port: 8181
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
security.ignored: /resources/**
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
